/// Realistic Financial Domain Catalog & Simulation Engine (F-01 to F-05)
/// Contains rich realistic fixtures for Wallets, Virtual Cards, Bill Payments,
/// Remittance v2, and P2P Trading.
class FinancialCatalog {
  static Map<String, dynamic> getBillServices() {
    return {
      'status': true,
      'message': 'Success',
      'data': {
        'countries': [
          {'name': 'ایران (Iran)', 'code': 'IR', 'dial_code': '+98'},
          {'name': 'امارات متحده (UAE)', 'code': 'AE', 'dial_code': '+971'},
          {'name': 'ترکیه (Turkey)', 'code': 'TR', 'dial_code': '+90'},
        ],
        'services': [
          {
            'id': 101,
            'name': 'همراه اول — شارژ مستقیم و بسته اینترنت',
            'code': 'mci_topup',
            'type': 'mobile',
            'operator': 'همراه اول (MCI)',
            'country_code': 'IR',
            'currency': 'IRR',
            'icon': 'https://ecardo.ir/icons/mci.png',
            'denominations': ['500000', '1000000', '2000000', '5000000'],
          },
          {
            'id': 102,
            'name': 'ایرانسل — شارژ شگفت‌انگیز و دیتا',
            'code': 'irancell_topup',
            'type': 'mobile',
            'operator': 'ایرانسل (MTN Irancell)',
            'country_code': 'IR',
            'currency': 'IRR',
            'icon': 'https://ecardo.ir/icons/irancell.png',
            'denominations': ['500000', '1000000', '2000000', '5000000'],
          },
          {
            'id': 103,
            'name': 'رایتل — اینترنت پرسرعت',
            'code': 'rightel_topup',
            'type': 'mobile',
            'operator': 'رایتل (RighTel)',
            'country_code': 'IR',
            'currency': 'IRR',
            'icon': 'https://ecardo.ir/icons/rightel.png',
            'denominations': ['500000', '1000000', '2000000'],
          },
          {
            'id': 201,
            'name': 'قبض برق سراسری',
            'code': 'electricity_bill',
            'type': 'utility',
            'operator': 'شرکت توانیر',
            'country_code': 'IR',
            'currency': 'IRR',
          },
          {
            'id': 202,
            'name': 'قبض گاز خانگی و تجاری',
            'code': 'gas_bill',
            'type': 'utility',
            'operator': 'شرکت ملی گاز',
            'country_code': 'IR',
            'currency': 'IRR',
          },
          {
            'id': 203,
            'name': 'قبض آب و فاضلاب',
            'code': 'water_bill',
            'type': 'utility',
            'operator': 'آب و فاضلاب کشور',
            'country_code': 'IR',
            'currency': 'IRR',
          },
        ],
        'history': [
          {
            'id': 1,
            'service_name': 'شارژ مستقیم همراه اول',
            'operator': 'همراه اول',
            'account_number': '09123456789',
            'amount': '1,000,000',
            'currency': 'IRR',
            'transaction_id': 'TXN-BILL-990142',
            'reference_id': 'REF-884192',
            'status': 'completed',
            'created_at': '2026-10-02 14:30:00',
          },
          {
            'id': 2,
            'service_name': 'قبض برق آپارتمان',
            'operator': 'توانیر',
            'account_number': '14829014829',
            'amount': '3,450,000',
            'currency': 'IRR',
            'transaction_id': 'TXN-BILL-990111',
            'reference_id': 'REF-881204',
            'status': 'completed',
            'created_at': '2026-09-25 10:15:00',
          },
        ],
      },
    };
  }

  static Map<String, dynamic> getCardProducts() {
    return {
      'status': 'success',
      'message': 'Success',
      'data': {
        'card_products': [
          {
            'id': 1,
            'name': 'MasterCard Virtual Platinum USD',
            'type': 'MasterCard',
            'currency': 'USD',
            'price': '10.00',
            'min_load': '10.00',
            'max_load': '10000.00',
            'daily_limit': '5000.00',
            'status': 'active',
            'features': ['پشتیبانی از اپل پی و پی‌پال', 'صدور آنی بدون کارمزد ماهانه', 'قابلیت شارژ مجدد نامحدود'],
          },
          {
            'id': 2,
            'name': 'Visa Gold Digital EUR',
            'type': 'Visa',
            'currency': 'EUR',
            'price': '12.00',
            'min_load': '20.00',
            'max_load': '15000.00',
            'daily_limit': '7500.00',
            'status': 'active',
            'features': ['پوشش کامل خریدهای اروپایی', '3D Secure پویا با پیامک', 'پشتیبانی از گوگل والت'],
          },
          {
            'id': 3,
            'name': 'PayCardo USDT Web3 Virtual',
            'type': 'EcardoPay',
            'currency': 'USDT',
            'price': '5.00',
            'min_load': '10.00',
            'max_load': '50000.00',
            'daily_limit': '20000.00',
            'status': 'active',
            'features': ['شارژ مستقیم از تتر TRC20 و ERC20', 'تسویه بدون کارمزد تبدیل ارزی'],
          },
        ],
        'cardholders': [
          {
            'id': 1,
            'name': 'کاربر دمو و تست کیفیت',
            'email': 'demo@ecardo.ir',
            'phone': '+989123456789',
            'status': 'verified',
          }
        ],
        'providers': [
          {'id': 1, 'name': 'MasterCard International', 'code': 'mastercard'},
          {'id': 2, 'name': 'Visa Worldwide', 'code': 'visa'},
          {'id': 3, 'name': 'Ecardo PayCardo Hub', 'code': 'ecardopay'},
        ],
      },
    };
  }

  static Map<String, dynamic> getRemittanceMethods() {
    return {
      'status': 'success',
      'message': 'Success',
      'data': {
        'corridors': [
          {
            'id': 1,
            'title': 'حواله درهم امارات (دبی و ابوظبی)',
            'country_code': 'AE',
            'country_name': 'امارات متحده عربی',
            'currency': 'AED',
            'rate_to_irr': 510800.0,
            'fixed_fee': 25.0,
            'percentage_fee': 0.4,
            'min_amount': 500.0,
            'max_amount': 200000.0,
            'delivery_time': 'کمتر از ۲ ساعت کاری',
            'payout_types': ['حساب بانکی (IBAN)', 'تحویل نقدی در دبی'],
          },
          {
            'id': 2,
            'title': 'حواله لیر ترکیه (استانبول و آنکارا)',
            'country_code': 'TR',
            'country_name': 'ترکیه',
            'currency': 'TRY',
            'rate_to_irr': 39100.0,
            'fixed_fee': 50.0,
            'percentage_fee': 0.5,
            'min_amount': 1000.0,
            'max_amount': 500000.0,
            'delivery_time': 'آنی از طریق سیستم FAST',
            'payout_types': ['حساب زراعت / ایش بانک', 'تحویل نقدی اکسچنج'],
          },
          {
            'id': 3,
            'title': 'حواله یورو اروپا (SEPA Instant)',
            'country_code': 'DE',
            'country_name': 'اتحادیه اروپا و آلمان',
            'currency': 'EUR',
            'rate_to_irr': 2167600.0,
            'fixed_fee': 8.0,
            'percentage_fee': 0.3,
            'min_amount': 100.0,
            'max_amount': 50000.0,
            'delivery_time': 'آنی (SEPA Instant)',
            'payout_types': ['شماره شبا اروپا (IBAN)'],
          },
          {
            'id': 4,
            'title': 'حواله پوند انگلستان (Faster Payments)',
            'country_code': 'GB',
            'country_name': 'بریتانیا',
            'currency': 'GBP',
            'rate_to_irr': 2540000.0,
            'fixed_fee': 10.0,
            'percentage_fee': 0.4,
            'min_amount': 100.0,
            'max_amount': 50000.0,
            'delivery_time': 'کمتر از ۱ ساعت',
            'payout_types': ['Sort Code & Account No'],
          },
        ],
        'remittances': [
          {
            'id': 1,
            'uuid': 'rem-ae-991204',
            'recipient_name': 'احمد رضایی (دبی)',
            'recipient_account': 'AE28033123456789012345',
            'send_amount': '1500.00',
            'send_currency': 'USD',
            'receive_amount': '5505.00',
            'receive_currency': 'AED',
            'rate': '3.67',
            'fee': '15.00',
            'status': 'completed',
            'tracking_code': 'REM-2026-99014',
            'created_at': '2026-10-01 12:40:00',
          },
          {
            'id': 2,
            'uuid': 'rem-tr-881230',
            'recipient_name': 'مریم کاظمی (استانبول)',
            'recipient_account': 'TR330001001234567890123456',
            'send_amount': '800.00',
            'send_currency': 'USD',
            'receive_amount': '27600.00',
            'receive_currency': 'TRY',
            'rate': '34.50',
            'fee': '8.00',
            'status': 'in_transit',
            'tracking_code': 'REM-2026-88129',
            'created_at': '2026-10-04 09:15:00',
          },
        ],
      },
    };
  }

  static Map<String, dynamic> getP2pMarketplace() {
    return {
      'status': 'success',
      'message': 'Success',
      'data': {
        'ads': [
          {
            'id': 101,
            'trader_name': 'صرافی آریا (Arya Exchange)',
            'trader_rating': 99.4,
            'trader_orders_count': 1420,
            'is_verified': true,
            'type': 'sell', // User buys USDT
            'crypto_currency': 'USDT',
            'fiat_currency': 'IRR',
            'price': '1882000',
            'min_limit': '50.0',
            'max_limit': '5000.0',
            'available_amount': '12400.0',
            'payment_methods': ['انتقال ساتنا / پایا', 'کارت به کارت'],
            'terms': 'واریز آنی در کمتر از ۵ دقیقه. فقط از حساب به نام خود خریدار.',
          },
          {
            'id': 102,
            'trader_name': 'امیرمحمد صراف (VIP Trader)',
            'trader_rating': 100.0,
            'trader_orders_count': 850,
            'is_verified': true,
            'type': 'buy', // User sells USDT
            'crypto_currency': 'USDT',
            'fiat_currency': 'IRR',
            'price': '1878000',
            'min_limit': '100.0',
            'max_limit': '10000.0',
            'available_amount': '25000.0',
            'payment_methods': ['ساتنا آنی بانکی'],
            'terms': 'تسویه ریالی فوری بلافاصله پس از آزادسازی تتر.',
          },
          {
            'id': 103,
            'trader_name': 'Dubai Fast OTC',
            'trader_rating': 98.9,
            'trader_orders_count': 610,
            'is_verified': true,
            'type': 'sell',
            'crypto_currency': 'USDT',
            'fiat_currency': 'AED',
            'price': '3.673',
            'min_limit': '500.0',
            'max_limit': '50000.0',
            'available_amount': '80000.0',
            'payment_methods': ['Emirates NBD', 'ADCB Transfer'],
            'terms': 'Local bank transfer within UAE. Instant release.',
          },
        ],
        'orders': [
          {
            'id': 991,
            'order_number': 'P2P-ORD-2026-99120',
            'trader_name': 'صرافی آریا',
            'type': 'buy',
            'crypto_amount': '250.00',
            'crypto_symbol': 'USDT',
            'fiat_amount': '470,500,000',
            'fiat_symbol': 'IRR',
            'status': 'completed',
            'created_at': '2026-10-02 16:10:00',
          },
        ],
        'payment_methods': [
          {'id': 1, 'name': 'کارت به کارت شتابی', 'type': 'card', 'currency': 'IRR'},
          {'id': 2, 'name': 'شماره شبا ساتنا/پایا', 'type': 'iban', 'currency': 'IRR'},
          {'id': 3, 'name': 'حساب بانکی امارات (IBAN AED)', 'type': 'bank', 'currency': 'AED'},
        ],
      },
    };
  }
}
