import java.util.Properties
import java.io.FileInputStream

plugins {
    id("com.android.application")
    id("com.google.gms.google-services")
    id("kotlin-android")
    id("dev.flutter.flutter-gradle-plugin")
}

// ============================================================================
// Release signing config
// ----------------------------------------------------------------------------
// v1.0.15+15 — CRITICAL FIX for "There was a problem while parsing the package"
//
// Root cause: when GitHub Secrets (SIGNING_KEYSTORE_BASE64 etc.) were not set,
// the previous code fell back to `signingConfigs.getByName("debug")`. With
// AGP 8.9+ and Flutter 3.44+, the default debug signing config does NOT
// auto-populate from ~/.android/debug.keystore on a fresh CI runner, so the
// release APK was being produced WITHOUT ANY SIGNATURE — Android refuses to
// install such APKs with the cryptic "parsing the package" error.
//
// Fix: ALWAYS ensure a usable keystore exists. If `key.properties` is present
// (CI with release secrets), use the real release keystore. Otherwise, create
// a deterministic debug keystore at `android/debug.keystore` on the fly and
// sign the release APK with it. This guarantees the APK is always installable,
// even on a fresh CI runner without any secrets configured.
//
// Production deployments SHOULD still set the four SIGNING_* secrets so that
// the same keystore is used across all builds (otherwise users cannot upgrade
// in-place — Android rejects signature changes between versions).
// ============================================================================
val keystoreProperties = Properties().apply {
    val keystoreFile = rootProject.file("key.properties")
    if (keystoreFile.exists()) {
        load(FileInputStream(keystoreFile))
    }
}

android {
    namespace = "com.ecardo.user"
    compileSdk = 36
    ndkVersion = "27.0.12077973"

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
        isCoreLibraryDesugaringEnabled = true
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11.toString()
    }

    defaultConfig {
        applicationId = "com.ecardo.user"
        minSdk = 24
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName

        // Guarantee all native ABIs are bundled so the APK installs on every
        // device architecture (arm64, arm32, x86_64). Without this, `flutter
        // build apk` may produce ABI-split APKs that fail to install on
        // devices whose ABI doesn't match the split.
        ndk {
            abiFilters += listOf("armeabi-v7a", "arm64-v8a", "x86_64")
        }
    }

    // -----------------------------------------------------------------------
    // Signing configs
    // -----------------------------------------------------------------------
    // 1. `release` — used when key.properties is present (CI with secrets).
    // 2. `debugFallback` — used when no release keystore is configured. We
    //    generate a deterministic debug keystore in `android/debug.keystore`
    //    via a gradle Exec task so the file always exists before signing.
    // -----------------------------------------------------------------------
    signingConfigs {
        create("release") {
            keystoreProperties["storeFile"]?.let { file(it) }?.let { storeFile = it }
            storePassword = keystoreProperties["storePassword"] as String?
            keyAlias = keystoreProperties["keyAlias"] as String?
            keyPassword = keystoreProperties["keyPassword"] as String?
        }
        create("debugFallback") {
            // Use a project-local keystore so builds are reproducible across
            // machines and CI runners. The file is generated by the
            // `ensureDebugKeystore` task below if it doesn't exist.
            storeFile = rootProject.file("debug.keystore")
            storePassword = "ecardo_debug_keystore"
            keyAlias = "ecardo-debug"
            keyPassword = "ecardo_debug_keystore"
        }
    }

    buildTypes {
        release {
            // Pick the right signing config: real release keystore when
            // key.properties exists, otherwise the deterministic debug fallback.
            // This GUARANTEES the APK is always signed.
            signingConfig = if (keystoreProperties.containsKey("storeFile")) {
                signingConfigs.getByName("release")
            } else {
                signingConfigs.getByName("debugFallback")
            }

            // v1.0.4+5: Enable R8 obfuscation + shrinking
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
        debug {
            isMinifyEnabled = false
            isShrinkResources = false
        }
    }
}

// ---------------------------------------------------------------------------
// Task: ensureDebugKeystore
// ---------------------------------------------------------------------------
// Creates `android/debug.keystore` if it doesn't already exist. Runs before
// any release assemble task. The keystore uses a fixed alias/password so the
// build is reproducible across CI runners. The keystore file is git-ignored
// (see .gitignore) — it's a build-time artifact, not a source asset.
// ---------------------------------------------------------------------------
tasks.register("ensureDebugKeystore") {
    val keystoreFile = rootProject.file("debug.keystore")
    outputs.file(keystoreFile)
    doLast {
        if (!keystoreFile.exists()) {
            logger.lifecycle("🔑 Generating debug fallback keystore at ${keystoreFile.absolutePath}")
            keystoreFile.parentFile.mkdirs()
            exec {
                commandLine(
                    "keytool",
                    "-genkeypair",
                    "-alias", "ecardo-debug",
                    "-keyalg", "RSA",
                    "-keysize", "2048",
                    "-validity", "10000",
                    "-keystore", keystoreFile.absolutePath,
                    "-storepass", "ecardo_debug_keystore",
                    "-keypass", "ecardo_debug_keystore",
                    "-dname", "CN=eCardo Debug, OU=Mobile, O=eCardo, L=Tehran, ST=Tehran, C=IR",
                    "-storetype", "PKCS12"
                )
            }
            logger.lifecycle("✅ Debug fallback keystore created")
        }
    }
}

// Hook the keystore-generation task to run before any release build.
tasks.matching { it.name.startsWith("assemble") && it.name.endsWith("Release") }
    .configureEach { dependsOn("ensureDebugKeystore") }

dependencies {
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.4")
}

flutter {
    source = "../.."
}
